### ISSUE TITLE
debspawn struggles building container for PureOS "landing"

### ISSUE THREAD

**Issue by jeremiah** [lkhq/debspawn#24]
The instructions for building a package in PureOS are to use debspawn with a "landing" argument, like this;

`$ debspawn build landing --sign`

The "landing" argument to debspawn designates the container image to build in, but if landing doesn't exist one needs to build it, which can be done with debspawn. This has to be done because we get the error;

`ERROR: The container image for "landing-amd64" does not exist. Please create it first.`

However, the usual debspawn way to create a container fails if you do not already have the name of the container as a script in debootstrap;

```
$ debspawn create landing
╔════════════════════════════════════════════╗
║  Creating new base: landing [amd64]        ║
╚════════════════════════════════════════════╝
Using mirror: default
Bootstrap suite: landing

┌───────────────────┐
│  Bootstrap        │
└───────────────────┘
E: No such script: /usr/share/debootstrap/scripts/landing
```
This is on an up to date debootstrap which still has the symlink of landing pointing to green. If the workaround is to symlink landing to byzantium, why not simply build for byzantium with debspawn and skip landing?

**Comment by ximion** [comment]
You will have to remove `green` (as that's not a valid suite anymore) and symlink `landing -> amber`. The script is the same, but the suite is different, so if you want to build for landing, you need a script available for landing - otherwise there's nothing debootstrap/debspawn can do.

As for why you want to build for landing: For PureOS `landing` has the most up-to-date packages, it is where your build dependencies are in the right versions and it is where the package will be uploaded. The `byzantium` suite has older stuff that went through a migration cycle. So to verify that your build actually works, you will have to build for `landing`.
